/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Output_Port_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_Output_Port_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/OutputPortStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {

/**
 * Provides a default implementation for OutputPortStubRemoteEvent and
 * OutputPortStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT OutputPortStubDefault
    : public virtual OutputPortStub {
public:
    COMMONAPI_EXPORT OutputPortStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(OutputPort::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT OutputPortStubRemoteEvent* initStubAdapter(const std::shared_ptr< OutputPortStubAdapter> &_adapter) {
        CommonAPI::Stub<OutputPortStubAdapter, OutputPortStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void setInput(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _Input, setInputReply_t _reply) {
        (void)_client;
        (void)_Input;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setPriority(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _Input, setPriorityReply_t _reply) {
        (void)_client;
        (void)_Input;
        std::string message = "";
        _reply(message);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual OutputPortStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(OutputPortStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        OutputPortStubDefault *defaultStub_;
    };
protected:
    OutputPortStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_Output_Port_STUB_DEFAULT
